package com.botmaker.studio.project.models;

import com.botmaker.plugin.api.value.ValueCatalog;
import com.botmaker.plugin.api.value.ValueContainer;
import com.botmaker.plugin.api.value.ValueForm;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A record instance and its class, written as one compilation unit the bot compiles.
 *
 * <p>The file is a holder: a {@code final class} with one constant, whose initialiser is the whole model
 * written out. The record type itself stays where it was declared — in the plugin's own jar, which the bot
 * already depends on — so the generated file adds a value and not a vocabulary, and a plugin that changes a
 * component's type breaks the bot's <em>build</em> rather than its next run. That is the whole point of
 * {@code docs/refactor/33-plugin-java.md}: every failure that used to be a silently empty value at runtime
 * becomes a compile error.
 *
 * <h2>Everything fully qualified, nothing imported</h2>
 *
 * <p>{@code ValueCatalog.initializer} already writes its half that way and says why: a fully qualified
 * initialiser compiles wherever it is placed. A generated file is placed by the host in a package the user
 * never chose, so it cannot be allowed to depend on the imports being right, and an import list is one more
 * thing that has to be regenerated identically or produce a diff. The file has none.
 *
 * <h2>Pure, like the validator</h2>
 *
 * <p>Class plus instance plus catalog in, source text out. No file is written here and no project is
 * consulted — {@link com.botmaker.studio.project.models.ModelGrammar} states the discipline and the reason.
 * Empty comes back for exactly one thing the validator could not have caught, a {@code null} held by a
 * component, because a legal type says nothing about what an instance of it holds.
 */
public final class ModelWriter {

    /** The constant a generated model is held in. The reader looks for this name and no other. */
    public static final String FIELD = "VALUE";

    private ModelWriter() {
    }

    /**
     * One compilation unit for {@code value}, or empty when any part of it cannot be written.
     *
     * <p>The class is taken from the instance, so a plugin cannot hand over a value of one type declared as
     * another. The header says what wrote the file and that editing it is pointless, which is the honest
     * half of {@code FileRole.GENERATED}: the role stops the editor, and the sentence tells a developer
     * reading the project on GitHub, with no Studio at all, where the content comes from.
     */
    public static Optional<String> compilationUnit(String packageName, String simpleName, Record value,
                                                   ValueCatalog catalog) {
        if (value == null || simpleName == null || simpleName.isBlank()) return Optional.empty();
        Class<?> type = value.getClass();
        if (!ModelGrammar.isLegal(type, catalog)) return Optional.empty();

        Optional<String> initializer = initializer(new ModelForm.Declared(type), value, catalog);
        if (initializer.isEmpty()) return Optional.empty();

        StringBuilder out = new StringBuilder();
        if (packageName != null && !packageName.isBlank()) {
            out.append("package ").append(packageName).append(";\n\n");
        }
        out.append("""
                /**
                 * Generated by BotMaker. Edits here are overwritten.
                 *
                 * <p>The model is changed in the editor that owns it; this file is what the bot compiles
                 * against, and it is rewritten whole every time that model is saved.
                 */
                """);
        out.append("public final class ").append(simpleName).append(" {\n\n");
        out.append("    /** The model, as the editor last saved it. */\n");
        out.append("    public static final ").append(type.getCanonicalName()).append(' ').append(FIELD)
                .append(" = ").append(initializer.get()).append(";\n\n");
        out.append("    private ").append(simpleName).append("() {\n    }\n}\n");
        return Optional.of(out.toString());
    }

    /**
     * {@code value} as the Java initialiser a field of type {@code form} would take.
     *
     * <p>The five cases are {@code 33}'s table, one method each, and none of them composes syntax of its
     * own: a container's call is whatever the container declared it to be, and a record's is its canonical
     * constructor. Empty propagates — one unwritable part makes the whole value unwritable, the same rule
     * {@code ValueCatalog.valueOf} applies to one unreadable item of a list, and for the same reason: half a
     * model written is worse than none.
     */
    public static Optional<String> initializer(ModelForm form, Object value, ValueCatalog catalog) {
        if (form == null || value == null) return Optional.empty();
        return switch (form) {
            case ModelForm.Builtin builtin -> literalOf(builtin.type(), value);
            case ModelForm.Constant ignored -> value instanceof Enum<?> constant
                    ? Optional.of(constant.getDeclaringClass().getCanonicalName() + "." + constant.name())
                    : Optional.empty();
            case ModelForm.Catalogued catalogued -> catalog == null
                    ? Optional.empty()
                    : catalog.initializer(ValueForm.of(catalogued.type()), value);
            case ModelForm.Composite composite -> composite(composite, value, catalog);
            case ModelForm.Declared declared -> declared(declared, value, catalog);
        };
    }

    private static Optional<String> composite(ModelForm.Composite form, Object value, ValueCatalog catalog) {
        ValueContainer<?> container = form.container();
        List<Object> parts = container.partsOf(value);
        Optional<List<ModelForm>> forms = ModelGrammar.partForms(form, parts.size());
        if (forms.isEmpty()) return Optional.empty();
        return call(container.factorySource(), forms.get(), parts, catalog);
    }

    private static Optional<String> declared(ModelForm.Declared form, Object value, ValueCatalog catalog) {
        if (!form.type().isInstance(value)) return Optional.empty();
        Optional<List<ModelGrammar.Component>> components =
                ModelGrammar.componentsOf(form.type(), catalog);
        if (components.isEmpty()) return Optional.empty();

        List<ModelForm> forms = components.get().stream().map(ModelGrammar.Component::form).toList();
        List<Object> parts = new ArrayList<>(forms.size());
        for (ModelGrammar.Component component : components.get()) {
            try {
                parts.add(component.component().getAccessor().invoke(value));
            } catch (IllegalAccessException | InvocationTargetException unreadable) {
                return Optional.empty();
            }
        }
        return call("new " + form.type().getCanonicalName(), forms, parts, catalog);
    }

    /** {@code callee(part, part, …)} — the one place a generated file grows a bracket. */
    private static Optional<String> call(String callee, List<ModelForm> forms, List<Object> parts,
                                         ValueCatalog catalog) {
        if (forms.size() != parts.size()) return Optional.empty();
        StringBuilder out = new StringBuilder(callee).append('(');
        for (int i = 0; i < parts.size(); i++) {
            Optional<String> part = initializer(forms.get(i), parts.get(i), catalog);
            if (part.isEmpty()) return Optional.empty();
            if (i > 0) out.append(", ");
            out.append(part.get());
        }
        return Optional.of(out.append(')').toString());
    }

    /**
     * A {@code String}, a primitive or a box as its own Java literal.
     *
     * <p>The suffixes and the casts are not decoration: {@code 3} is an {@code int} and a component declared
     * {@code long} takes it, but a component declared {@code byte} does not take {@code 3} inside a
     * constructor call, and {@code 1.0} is not a {@code float}. Each row here is the spelling that compiles
     * in argument position, which is the only position this writer ever produces.
     *
     * <p>A non-finite {@code double} is written as the constant that names it, because {@code NaN} is not a
     * literal in any Java grammar, and a model holding one is a legal model.
     */
    private static Optional<String> literalOf(Class<?> type, Object value) {
        return switch (value) {
            case String text -> Optional.of(quoted(text));
            case Boolean flag -> Optional.of(flag.toString());
            case Character character -> Optional.of(character(character));
            case Byte number -> Optional.of("(byte) " + number);
            case Short number -> Optional.of("(short) " + number);
            case Integer number -> Optional.of(type == long.class || type == Long.class
                    ? number + "L" : number.toString());
            case Long number -> Optional.of(number + "L");
            case Float number -> Optional.of(finite(number.doubleValue())
                    ? number + "f" : "Float." + special(number.doubleValue()));
            case Double number -> Optional.of(finite(number)
                    ? number.toString() : "Double." + special(number));
            default -> Optional.empty();
        };
    }

    private static boolean finite(double number) {
        return !Double.isNaN(number) && !Double.isInfinite(number);
    }

    private static String special(double number) {
        if (Double.isNaN(number)) return "NaN";
        return number > 0 ? "POSITIVE_INFINITY" : "NEGATIVE_INFINITY";
    }

    private static String quoted(String text) {
        StringBuilder out = new StringBuilder(text.length() + 2).append('"');
        text.codePoints().forEach(point -> out.append(escaped(point, '"')));
        return out.append('"').toString();
    }

    private static String character(char value) {
        return "'" + escaped(value, '\'') + "'";
    }

    /**
     * One character as it is written inside quotes.
     *
     * <p>Anything outside printable ASCII becomes a {@code \\u} escape rather than being written through.
     * The file is compiled by whatever javac the user has, with whatever {@code -encoding} their pom sets,
     * and a model holding a name in a script Studio never anticipated must not turn into mojibake in their
     * source tree.
     */
    private static String escaped(int point, char quote) {
        return switch (point) {
            case '\\' -> "\\\\";
            case '\n' -> "\\n";
            case '\r' -> "\\r";
            case '\t' -> "\\t";
            case '\b' -> "\\b";
            case '\f' -> "\\f";
            default -> {
                if (point == quote) yield "\\" + quote;
                if (point < 0x20 || point > 0x7e) {
                    StringBuilder out = new StringBuilder(12);
                    for (char unit : Character.toChars(point)) {
                        out.append(String.format("\\u%04x", (int) unit));
                    }
                    yield out.toString();
                }
                yield String.valueOf((char) point);
            }
        };
    }
}
